serial.write_line("Starting BBC micro:bit [" + ("" + control.device_name() + "]"))
bluetooth.start_led_service()
bluetooth.start_temperature_service()
bluetooth.start_accelerometer_service()
bluetooth.start_magnetometer_service()
bluetooth.start_button_service()
bluetooth.start_io_pin_service()
serial.write_line("Go!")
basic.show_icon(IconNames.HAPPY)